models:
    name: yolov8m             # 模型输出名称
    platform: onnx            # 原始模型使用的框架
    model_file_path: weights/yolov8m.onnx # 原模型路径
    subgraphs:                   # 描述输入输出shape等信息
      input_size_list:
        - 1, 3, 640, 640
    quantize: False              # QAT已经量化过，不需要再量化
    configs:
      mean_values: [0, 0, 0]       
      std_values: [255, 255, 255]  
      #mean_values: [123.675, 116.28, 103.53]  # rknn.config的mean_values参数
      #std_values: [58.395, 58.395, 58.395]    # rknn.config的std_values参数
      quant_img_RGB2BGR: False     # 不进行RGB2BGR转换
